"""HTTP path bindings for WebSocket actions (dual registration)."""

from app.api.protocol import Action

# (method, path, action, path_param_map)
HTTP_BINDINGS: list[tuple[str, str, str, dict[str, str] | None]] = [
    ("GET", "/api/v1/account", Action.GET_ACCOUNT, None),
    ("GET", "/api/v1/history", Action.GET_HISTORY, None),
    ("GET", "/api/v1/market/{symbol}/candles", Action.SUBSCRIBE_SYMBOL, {"symbol": "symbol"}),
    ("GET", "/api/v1/market/{symbol}/history", Action.GET_MARKET_HISTORY, {"symbol": "symbol"}),
    ("POST", "/api/v1/orders", Action.PLACE_ORDER, None),
    ("POST", "/api/v1/orders/preview", Action.PREVIEW_ORDER, None),
    ("DELETE", "/api/v1/orders/{order_id}", Action.CANCEL_ORDER, {"order_id": "order_id"}),
    ("PATCH", "/api/v1/positions/{symbol}/sl-tp", Action.UPDATE_POSITION_SL_TP, {"symbol": "symbol"}),
    ("GET", "/api/v1/bots", Action.BOT_GET_ALL, None),
    ("GET", "/api/v1/bots/all", Action.BOT_LIST_ALL, None),
    ("POST", "/api/v1/bots", Action.BOT_CREATE, None),
    ("GET", "/api/v1/bots/{bot_id}", Action.BOT_GET_DETAIL, {"bot_id": "bot_id"}),
    ("PATCH", "/api/v1/bots/{bot_id}/config", Action.BOT_UPDATE_CONFIG, {"bot_id": "bot_id"}),
    ("POST", "/api/v1/bots/{bot_id}/stop", Action.BOT_STOP, {"bot_id": "bot_id"}),
    ("POST", "/api/v1/bots/{bot_id}/pause", Action.BOT_PAUSE, {"bot_id": "bot_id"}),
    ("POST", "/api/v1/bots/{bot_id}/resume", Action.BOT_RESUME, {"bot_id": "bot_id"}),
    ("POST", "/api/v1/bots/stop-all", Action.BOT_STOP_ALL, None),
    ("POST", "/api/v1/backtest", Action.RUN_BACKTEST, None),
    ("POST", "/api/v1/backtest/sweep", Action.RUN_BACKTEST_SWEEP, None),
    ("POST", "/api/v1/backtest/cancel", Action.CANCEL_BACKTEST, None),
    ("POST", "/api/v1/agent/analyze", Action.CHART_ANALYZE, None),
    ("POST", "/api/v1/agent/deep-reason", Action.CHART_DEEP_REASON, None),
    ("POST", "/api/v1/agent/explain-trade", Action.EXPLAIN_TRADE, None),
    ("POST", "/api/v1/scanner/scan", Action.MARKET_SCAN, None),
    ("POST", "/api/v1/agent/vision", Action.CHART_VISION, None),
    ("POST", "/api/v1/analytics", Action.ANALYTICS_GET, None),
    ("GET", "/api/v1/journal", Action.JOURNAL_LIST, None),
    ("POST", "/api/v1/journal", Action.JOURNAL_UPSERT, None),
    ("DELETE", "/api/v1/journal/{id}", Action.JOURNAL_DELETE, {"id": "id"}),
    ("GET", "/api/v1/chart-drawings/{symbol}", Action.CHART_DRAWINGS_GET, {"symbol": "symbol"}),
    ("POST", "/api/v1/chart-drawings/{symbol}", Action.CHART_DRAWINGS_SET, {"symbol": "symbol"}),
    ("GET", "/api/v1/admin/stats", Action.ADMIN_GET_STATS, None),
    ("POST", "/api/v1/admin/archive/backfill", Action.ADMIN_ARCHIVE_BACKFILL, None),
    ("POST", "/api/v1/admin/archive/export", Action.ADMIN_ARCHIVE_EXPORT, None),
    ("POST", "/api/v1/admin/archive/import", Action.ADMIN_ARCHIVE_IMPORT, None),
    ("GET", "/api/v1/admin/reconciliation", Action.ADMIN_GET_RECONCILIATION, None),
    ("POST", "/api/v1/admin/reconciliation/reconcile", Action.ADMIN_RECONCILE, None),
    ("POST", "/api/v1/admin/reconciliation/resolve", Action.ADMIN_RESOLVE_AMBIGUOUS, None),
    ("GET", "/api/v1/admin/safe-mode", Action.ADMIN_GET_SAFE_MODE, None),
    ("POST", "/api/v1/admin/safe-mode/confirm", Action.ADMIN_CONFIRM_SAFE_MODE, None),
    ("GET", "/api/v1/market/{symbol}/ticks", Action.GET_MARKET_TICKS, {"symbol": "symbol"}),
    ("POST", "/api/v1/admin/simulation", Action.ADMIN_SET_SIMULATION, None),
    ("POST", "/api/v1/admin/seed-balance", Action.ADMIN_SEED_BALANCE, None),
    ("POST", "/api/v1/admin/reset", Action.ADMIN_RESET_SYSTEM, None),
    ("POST", "/api/v1/admin/emergency-stop", Action.ADMIN_EMERGENCY_STOP, None),
    ("POST", "/api/v1/admin/risk/reset-kill-switch", Action.ADMIN_RESET_RISK_KILL_SWITCH, None),
    ("GET", "/api/v1/notifications/channels", Action.NOTIFY_CHANNEL_LIST, None),
    ("POST", "/api/v1/notifications/channels", Action.NOTIFY_CHANNEL_UPSERT, None),
    ("DELETE", "/api/v1/notifications/channels/{id}", Action.NOTIFY_CHANNEL_DELETE, {"id": "id"}),
    ("POST", "/api/v1/notifications/channels/{id}/test", Action.NOTIFY_CHANNEL_TEST, {"id": "id"}),
    ("POST", "/api/v1/notifications/digest/send", Action.NOTIFY_DIGEST_SEND_NOW, None),
    ("GET", "/api/v1/alerts/rules", Action.ALERT_RULE_LIST, None),
    ("POST", "/api/v1/alerts/rules", Action.ALERT_RULE_UPSERT, None),
    ("DELETE", "/api/v1/alerts/rules/{id}", Action.ALERT_RULE_DELETE, {"id": "id"}),
    ("GET", "/api/v1/alerts/history", Action.ALERT_RULE_HISTORY, None),
    ("GET", "/api/v1/notifications/push/vapid-public-key", Action.NOTIFY_PUSH_VAPID_PUBLIC, None),
    ("POST", "/api/v1/notifications/push/subscribe", Action.NOTIFY_PUSH_SUBSCRIBE, None),
    ("POST", "/api/v1/notifications/push/unsubscribe", Action.NOTIFY_PUSH_UNSUBSCRIBE, None),
    ("GET", "/api/v1/notifications/push/subscriptions", Action.NOTIFY_PUSH_LIST, None),
    ("GET", "/api/v1/risk/config", Action.RISK_GET_CONFIG, None),
    ("POST", "/api/v1/risk/preview", Action.RISK_PREVIEW_ENTRY, None),
    ("POST", "/api/v1/risk/basket-correlation", Action.RISK_BASKET_CORRELATION, None),
]
